//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsCart
    {
        public int CartID { get; set; }
        public int UserID { get; set; }
        public int SupplementsID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Supplement Supplement { get; set; }
        public virtual User User { get; set; }
    }
}
